introduccion= input("Buen dia estimado lector, para la realizacion de esta practica necesito que pienses que tus tres municipios favoritos de Sinaloa, cuando estes listo puedes decirme cual es tu animal favorito: ")
municipio1= input("Ingresa el nombre del municipio 1: ")
municipio2= input("Ingresa el nombre del municipio 2: ")
municipio3= input("Ingresa el nombre del municipio 3: ")
print("Muchas gracias, ahora necesito que me coloques el numero de habitantes de cada municipio")
habitantes1= int(input("Ingresa el numero de habitantes del municipio de "+municipio1+":"))
habitantes2= int(input("Ingresa el numero de habitantes del municipio de "+municipio2+":"))
habitantes3= int(input("Ingresa el numero de habitantes del municipio de "+municipio3+":"))
lista_municipios= [municipio1, municipio2, municipio3]
print("Sus municipios favoritos del Estado de Sinaloa son: ")
print(lista_municipios)
total_habitantes= (habitantes1+habitantes2+habitantes3)
promedio_habitantes= (total_habitantes/3)
print(" El total de habitantes de sus municipios favoritos es de :"+str(total_habitantes)+ " mientras que el promedio de personas es de : "+str(promedio_habitantes))
